name: close_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - tesseract
  - poppler
  - libtiff
  - pip
  - pandas
  - pdfplumber
  - streamlit
  - pip:
      - pytesseract
      - pillow
      - pdf2image
      - pymupdf
      - langchain>=0.1.0
      - langchain-google-genai
      - langchain-community
      - langchain-chroma
      - chromadb
      - google-generativeai
      - python-dotenv
      - tabulate
      - jupyter
